name: Publish npm Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Lint and Test
        run: |
          npm run lint
          npm test

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: npm publish
